### ISSUE TITLE
消费端幂等不能百分之百保证

### ISSUE THREAD

**Issue by liuqingyu** [TaXueWWL/seckill-rocketmq#2]
通过插入前校验不能保证百分之百幂等，在高并发下仍然可能出现问题，最好在数据库层加一个唯一索引保证或加一个防重表来做最后的保证

**Comment by TaXueWWL** [comment]
> 通过插入前校验不能保证百分之百幂等，在高并发下仍然可能出现问题，最好在数据库层加一个唯一索引保证或加一个防重表来做最后的保证

订单号有唯一索引

**Comment by TaXueWWL** [comment]
> 通过插入前校验不能保证百分之百幂等，在高并发下仍然可能出现问题，最好在数据库层加一个唯一索引保证或加一个防重表来做最后的保证

实际开发的时候使用MySQL等数据库会添加索引，这个案例本身只是个demo，用的H2。多谢建议

**Comment by wangjia2016** [comment]
用订单号唯一索引呗 发消息到mq的时候 就传订单号
