### ISSUE TITLE
扣减库存没有加锁，应该会导致超卖

### ISSUE THREAD

**Issue by wangjia2016** [TaXueWWL/seckill-rocketmq#8]
扣减库存没有加锁，应该会导致超卖

**Comment by TaXueWWL** [comment]
请给出代码举例，谢谢

**Comment by TaXueWWL** [comment]
库存校验在数据库层有乐观锁保证，进程内就不需要再额外加锁了，反正你也锁不住。

**Comment by TaXueWWL** [comment]
库存校验在数据库层有乐观锁保证，进程内就不需要再额外加锁了，反正你也锁不住。
除非用分布式锁，但是有乐观锁了再搞个分布式锁，没必要。

**Comment by wangjia2016** [comment]
@TaXueWWL 秒杀场景 数据库分库、分表的情况下，如何用数据库陈的乐观锁
分布式锁的话 性能也是个问题
